### ISSUE TITLE
UnBound Local Error Uploading one's own Timbre Transfer Model

### ISSUE THREAD

**Issue by Goingcaine** [magenta/ddsp#83]
Hi everyone,

I have tried multiple times to upload my own audio model to no success... It always works with the existing models such as the violin and trumpet, but every time I try to upload my model the following error occurs. 

<img width="1081" alt="Captura de ecrã 2020-04-23, às 12 40 05" src="https://user-images.githubusercontent.com/64257501/80202091-65ea7e80-8625-11ea-90e6-9b75955c52e8.png">

Could anyone help me please? I would really appreciate it. 

Best regards

**Comment by kcbuilder01** [comment]
Hey this happened to me, should be an easy fix. If you downloaded your model from the other autoencoder colab it may have downloaded partially. I fixed this by going to google drive, finding the complete model checkpoint there and downloaded it correctly.

**Comment by Goingcaine** [comment]
Hey,

Thank you so much for replying. I still can't get it to work, but my knowledge is close to no existing in regards to programming.  I have clicked on the copy to drive and ran the system this way, as you can see in the picture below.

<img width="592" alt="Captura de ecrã 2020-04-25, às 14 44 27" src="https://user-images.githubusercontent.com/64257501/80280274-55103a80-8703-11ea-89b2-2c15a7652e92.png">

I still got the same error.
Is this how I use the model from google drive? Could you tell me how to do it step by step please?

I would really appreciate it.

Best regards and thanks for such a quick reply.

**Comment by kcbuilder01** [comment]
No worries. The checkpoint folder that you downloaded from the autoencoder colab should be stored in your actual google drive account. So leave the colab tab, open a new tab and go to google drive. Search for your checkpoint folder there and when you locate it, download it. Then try to upload this version of your checkpoint folder to the timbre transfer colab. Hopefully this works.

**Comment by Goingcaine** [comment]
Hey, thanks again for replying. It is still not working. I have download the folder, uploaded it to a blank google collab page and still get the same mistake. 

I have downloaded it from drive and uploaded it to collab, opened directly from drive to collab and still get the same issue. 
<img width="1246" alt="Captura de ecrã 2020-04-28, às 14 31 15" src="https://user-images.githubusercontent.com/64257501/80487606-65bbed00-895d-11ea-92d8-c3e3dcbaf0a2.png">

<img width="394" alt="Captura de ecrã 2020-04-28, às 14 31 49" src="https://user-images.githubusercontent.com/64257501/80487712-88e69c80-895d-11ea-8062-03c198721d29.png">
<img width="358" alt="Captura de ecrã 2020-04-28, às 14 31 57" src="https://user-images.githubusercontent.com/64257501/80487731-8c7a2380-895d-11ea-9d77-657706c46abe.png">

I have also the .ipynb from timbre transfer and uploaded it to collab but still have the exact same error : /. 

Is there anything that I am doing a wrong ? 

I would really appreciate the ability to use this model. 

Kind regards

**Comment by jesseengel** [comment]
I'm sorry you're having trouble with this, the workflow that I've tested is to train using the [train_autoencoder.ipynb](https://github.com/magenta/ddsp/blob/master/ddsp/colab/demos/train_autoencoder.ipynb) notebook and download the zip file at the end (that contains the trained model directory) using the coding prompt, it should be named `my_solo_instrument.zip`. Then to upload that exact zip file in timbre_tranfer.ipynb notebook.

**Comment by jesseengel** [comment]
I've tried this several times sucessfully now, so I'm going to close this for now.
